# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Xilinx/Vivado_code/Question_9/Alu_DSP/Alu_DSP.cache/wt [current_project]
set_property parent.project_path F:/Xilinx/Vivado_code/Question_9/Alu_DSP/Alu_DSP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip f:/Xilinx/Vivado_code/Question_9/Alu_DSP/Alu_DSP.srcs/sources_1/ip/xbip_dsp48_macro_0/xbip_dsp48_macro_0.xci
set_property is_locked true [get_files f:/Xilinx/Vivado_code/Question_9/Alu_DSP/Alu_DSP.srcs/sources_1/ip/xbip_dsp48_macro_0/xbip_dsp48_macro_0.xci]

synth_design -top xbip_dsp48_macro_0 -part xc7k70tfbv676-1 -max_dsp 50 -cascade_dsp force
write_checkpoint -noxdef xbip_dsp48_macro_0.dcp
catch { report_utilization -file xbip_dsp48_macro_0_utilization_synth.rpt -pb xbip_dsp48_macro_0_utilization_synth.pb }
