# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Xilinx/Vivado_code/Question_2/erotima_2/erotima_2.cache/wt [current_project]
set_property parent.project_path F:/Xilinx/Vivado_code/Question_2/erotima_2/erotima_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Πάνος/Desktop/vivado code_1/Ερώτημα_2/erotima_2/erotima_2.srcs/sources_1/new/or_gate.vhd}
  {C:/Users/Πάνος/Desktop/vivado code_1/Ερώτημα_2/erotima_2/erotima_2.srcs/sources_1/new/not_gate.vhd}
  {C:/Users/Πάνος/Desktop/vivado code_1/Ερώτημα_2/erotima_2/erotima_2.srcs/sources_1/new/and_gate.vhd}
  {C:/Users/Πάνος/Desktop/vivado code_1/Ερώτημα_2/erotima_2/erotima_2.srcs/sources_1/new/Fuction_full.vhd}
}
synth_design -top Fuction_full -part xc7k70tfbv676-1
write_checkpoint -noxdef Fuction_full.dcp
catch { report_utilization -file Fuction_full_utilization_synth.rpt -pb Fuction_full_utilization_synth.pb }
