set_load 0.000 [all_outputs]



set_load 0.000 [all_outputs]



set_load 0.000 [all_outputs]



set_load 0.000 [all_outputs]
set_load 0.000 [all_outputs]
set_property LOAD 0 [get_ports {result[7]}]
set_property LOAD 0 [get_ports {result[26]}]
set_property LOAD 0 [get_ports {result[10]}]
set_property LOAD 0 [get_ports {result[5]}]
set_property LOAD 0 [get_ports {result[24]}]
set_property LOAD 0 [get_ports {result[55]}]
set_property LOAD 0 [get_ports {result[2]}]
set_property LOAD 0 [get_ports {result[25]}]
set_property LOAD 0 [get_ports {result[57]}]
set_property LOAD 0 [get_ports {result[40]}]
set_property LOAD 0 [get_ports {result[45]}]
set_property LOAD 0 [get_ports {result[50]}]
set_property LOAD 0 [get_ports {result[0]}]
set_property LOAD 0 [get_ports {result[15]}]
set_property LOAD 0 [get_ports {result[35]}]
set_property LOAD 0 [get_ports {result[34]}]
set_property LOAD 0 [get_ports {result[11]}]
set_property LOAD 0 [get_ports {result[13]}]
set_property LOAD 0 [get_ports {result[39]}]
set_property LOAD 0 [get_ports {result[60]}]
set_property LOAD 0 [get_ports {result[38]}]
set_property LOAD 0 [get_ports {result[6]}]
set_property LOAD 0 [get_ports {result[16]}]
set_property LOAD 0 [get_ports {result[28]}]
set_property LOAD 0 [get_ports {result[33]}]
set_property LOAD 0 [get_ports {result[41]}]
set_property LOAD 0 [get_ports {result[4]}]
set_property LOAD 0 [get_ports {result[59]}]
set_property LOAD 0 [get_ports {result[27]}]
set_property LOAD 0 [get_ports {result[22]}]
set_property LOAD 0 [get_ports {result[9]}]
set_property LOAD 0 [get_ports {result[54]}]
set_property LOAD 0 [get_ports {result[42]}]
set_property LOAD 0 [get_ports {result[29]}]
set_property LOAD 0 [get_ports {result[53]}]
set_property LOAD 0 [get_ports {result[18]}]
set_property LOAD 0 [get_ports {result[8]}]
set_property LOAD 0 [get_ports {result[48]}]
set_property LOAD 0 [get_ports {result[58]}]
set_property LOAD 0 [get_ports {result[43]}]
set_property LOAD 0 [get_ports {result[21]}]
set_property LOAD 0 [get_ports {result[63]}]
set_property LOAD 0 [get_ports {result[1]}]
set_property LOAD 0 [get_ports {result[36]}]
set_property LOAD 0 [get_ports {result[19]}]
set_property LOAD 0 [get_ports {result[31]}]
set_property LOAD 0 [get_ports {result[14]}]
set_property LOAD 0 [get_ports {result[47]}]
set_property LOAD 0 [get_ports {result[46]}]
set_property LOAD 0 [get_ports {result[23]}]
set_property LOAD 0 [get_ports {result[12]}]
set_property LOAD 0 [get_ports {result[17]}]
set_property LOAD 0 [get_ports {result[20]}]
set_property LOAD 0 [get_ports {result[30]}]
set_property LOAD 0 [get_ports {result[32]}]
set_property LOAD 0 [get_ports {result[37]}]
set_property LOAD 0 [get_ports {result[3]}]
set_property LOAD 0 [get_ports {result[44]}]
set_property LOAD 0 [get_ports {result[49]}]
set_property LOAD 0 [get_ports {result[51]}]
set_property LOAD 0 [get_ports {result[52]}]
set_property LOAD 0 [get_ports {result[56]}]
set_property LOAD 0 [get_ports {result[61]}]
set_property LOAD 0 [get_ports {result[62]}]
set_load 0.000 [all_outputs]
