set_property LOAD 0 [get_ports {S[0]}]
set_property LOAD 0 [get_ports Cout]
set_property LOAD 0 [get_ports {S[1]}]
set_property LOAD 0 [get_ports {S[2]}]
set_property LOAD 0 [get_ports {S[3]}]
set_load 0.000 [all_outputs]
