# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Xilinx/Vivado_code/Question_5/multiplier_with_half_adder/multiplier_with_half_adder.cache/wt [current_project]
set_property parent.project_path F:/Xilinx/Vivado_code/Question_5/multiplier_with_half_adder/multiplier_with_half_adder.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Πάνος/Desktop/vivado code_1/Ερώτημα_5/_5/multiplier_with_half_adder/multiplier_with_half_adder.srcs/sources_1/new/Halfadder.vhd}
  {C:/Users/Πάνος/Desktop/vivado code_1/Ερώτημα_5/_5/multiplier_with_half_adder/multiplier_with_half_adder.srcs/sources_1/new/multiplier2x2.vhd}
}
synth_design -top multiplier2x2 -part xc7k70tfbv676-1
write_checkpoint -noxdef multiplier2x2.dcp
catch { report_utilization -file multiplier2x2_utilization_synth.rpt -pb multiplier2x2_utilization_synth.pb }
