# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Xilinx/Vivado_code/Question_9/Alu_DSP/Alu_DSP.cache/wt [current_project]
set_property parent.project_path F:/Xilinx/Vivado_code/Question_9/Alu_DSP/Alu_DSP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib E:/vivado/project_1/project_1.srcs/sources_1/new/cond_arch.vhd
synth_design -top simple_alu -part xc7k70tfbv676-1 -max_dsp 100 -cascade_dsp force
write_checkpoint -noxdef simple_alu.dcp
catch { report_utilization -file simple_alu_utilization_synth.rpt -pb simple_alu_utilization_synth.pb }
