set_property LOAD 0 [get_ports c_xnor]
set_property LOAD 0 [get_ports c_or]
set_property LOAD 0 [get_ports c_nand]
set_property LOAD 0 [get_ports c_not]
set_property LOAD 0 [get_ports c_and]
set_property LOAD 0 [get_ports c_nor]
set_property LOAD 0 [get_ports c_xor]
set_load 0.000 [all_outputs]
