# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xa7a15tcpg236-2I

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Xilinx/Vivado_code/Question_1/Fuction_1/Fuction_1.cache/wt [current_project]
set_property parent.project_path F:/Xilinx/Vivado_code/Question_1/Fuction_1/Fuction_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/Πάνος/Desktop/vivado code_1/Ερώτημα_1/Fuction_1/Fuction_1.srcs/sources_1/new/Fuction1.vhd}}
read_xdc F:/Xilinx/Vivado_code/Question_1/Fuction_1/Fuction_1.srcs/constrs_1/new/Fuction1.xdc
set_property used_in_implementation false [get_files F:/Xilinx/Vivado_code/Question_1/Fuction_1/Fuction_1.srcs/constrs_1/new/Fuction1.xdc]

synth_design -top Fuction1 -part xa7a15tcpg236-2I
write_checkpoint -noxdef Fuction1.dcp
catch { report_utilization -file Fuction1_utilization_synth.rpt -pb Fuction1_utilization_synth.pb }
