# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Xilinx/Vivado_code/Question_7/erotima_7/erotima_7.cache/wt [current_project]
set_property parent.project_path F:/Xilinx/Vivado_code/Question_7/erotima_7/erotima_7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib E:/vivado/erotimata_apo_pc_giorgou/erotima_7/erotima_7.srcs/sources_1/new/erotima_7.vhd
synth_design -top erotima_7 -part xc7k70tfbv676-1
write_checkpoint -noxdef erotima_7.dcp
catch { report_utilization -file erotima_7_utilization_synth.rpt -pb erotima_7_utilization_synth.pb }
