# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Xilinx/Vivado_code/Question_5/simple_multiplier/simple_multiplier.cache/wt [current_project]
set_property parent.project_path F:/Xilinx/Vivado_code/Question_5/simple_multiplier/simple_multiplier.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib F:/Xilinx/Vivado_code/Question_5/simple_multiplier/simple_multiplier.srcs/sources_1/new/Multiplier_VHDL.vhd
synth_design -top Multiplier_VHDL -part xc7k70tfbv676-1
write_checkpoint -noxdef Multiplier_VHDL.dcp
catch { report_utilization -file Multiplier_VHDL_utilization_synth.rpt -pb Multiplier_VHDL_utilization_synth.pb }
