set_property LOAD 0 [get_ports Done]
set_property LOAD 0 [get_ports {Quotient[1]}]
set_property LOAD 0 [get_ports {Quotient[3]}]
set_property LOAD 0 [get_ports {Quotient[0]}]
set_property LOAD 0 [get_ports {Remainder[0]}]
set_property LOAD 0 [get_ports {Remainder[2]}]
set_property LOAD 0 [get_ports {Quotient[2]}]
set_property LOAD 0 [get_ports {Remainder[3]}]
set_property LOAD 0 [get_ports {Remainder[1]}]
set_load 0.000 [all_outputs]
